### ISSUE TITLE
This isn't just about metrics.

### ISSUE THREAD

**Issue by tony1athome** [marisolpalmero/GREEN-bof#1]
While I value having metrics both from a managerial perspective and within routing protocols, this BoF (and WG) shouldn't just be about metrics. It should also be about actually putting in place technology that improves our sustainability and power consumption. Therefore, I propose removing 'metrics' from the name and changing the description to broaden the topic. This applies to both the BoF creation and WG creation documents.

**Comment by marisolpalmero** [comment]
note from Toerless to the group attending the 1st BOF proposal call, also related to the name:

*******
I will think about more substantial feedback in time.

Right now, i can not resist to suggest a name for the to-be WG that
can easily be abbreviated:

Green Metrics Operations

;-))

I love weird humor. But in any case, calling it _just_ green without further qualification
might be a bit too broad.

Cheers
   toerless

**Comment by marisolpalmero** [comment]
New Proposal has been created and updated under "GreenCharterProposal.md" file, considering this issue created by Tony Li.
