### ISSUE TITLE
where is the home for draft-cparsk-eimpact-sustainability-considerations

### ISSUE THREAD

**Issue by billwuqin** [marisolpalmero/GREEN-bof#12]
I am wondering where is the right place to proceed draft-cparsk-eimpact-sustainability-considerations?E-Impact or this proposed WG? I know E-impact targets to broad scope and help build a whole picture with collaboration with other orgnizations or community,
will not specify any IETF protocol work or mechanism work? It seems draft-cparsk-eimpact-sustainability-considerations is more fitted into scope of E-impact. Do we need to draw boundary between E-impact and this proposed WG.

**Comment by cpignata** [comment]
@billwuqin , e-impact, as per Suresh, cannot publish (or is at best very limited and constrained into this).

Defining a "boundary" between e-impact and this proposed WG seems counter to defining a **bridge**...

draft-cparsk-eimpact-sustainability-considerations is being split into 3 documents, as per discussion on e-impact.

**Comment by sureshkrishnan** [comment]
Yes. As Carlos mentioned above, the draft is being split into three parts and my personal view is that the terminology part is related to the charter mentioned here.

**Comment by marisolpalmero** [comment]
Terminology as part of Work Items considers the draft already. Closing the issue.
