### ISSUE TITLE
What is "A framework that will enable the collection, aggregation and consumption (..)" ?

### ISSUE THREAD

**Issue by mwelzl** [marisolpalmero/GREEN-bof#13]
I'm asking because the out-of-scope list, as it currently stands, calls out the ICMP extensions as a "Network Quality Analysis (NQA) technique to understand the impact of energy efficiency optimization on service quality".

That surprises me: I would have thought that ICMP extensions are one out of many possible ways to collect the data (for consumption in whatever way), matching the sentence under "goals and scope".

The suggestion in #6 resolves the problem I see with the out-of-scope list, but still, my question is: if the ICMP extensions are not a  way (one out of many possible) to "enable the collection, .. and consumption, ...", then what else is?  I just wonder what's meant with that "framework".

**Comment by billwuqin** [comment]
See relevant discussion: https://github.com/billwuqin/Green-Energy-Network/issues/4
Based on discussion, I think this work is not high priority at the initial phase.

**Comment by mwelzl** [comment]
You didn't read my message. I understand that ICMP extensions are out of scope (for now), and this is not what I'm asking about.

**Comment by dhruvdhody** [comment]
I guess, it would be similar to a network telemetry collection system based on NETCONF/RESTCONF/YANG...

**Comment by tony1athome** [comment]
Telemetry is existing technology. Creating a duplicate would not be welcome. 

Could we please be more specific than saying 'framework'?  Is that a Python package? Or an architecture document?

**Comment by marisolpalmero** [comment]
latest charter proposal already addressed this comment. Closing it.
