### ISSUE TITLE
Draft names in work items

### ISSUE THREAD

**Issue by sureshkrishnan** [marisolpalmero/GREEN-bof#16]
The charter should mention the conceptual content of the work items instead of simply discussing candidate draft names.

**Comment by dhruvdhody** [comment]
+1

**Comment by snmitrov** [comment]
I've made some edit/suggestions and submitted a PR.

**Comment by billwuqin** [comment]
Your proposed edit is too specific, seems not suitable for charter text.

**Comment by billwuqin** [comment]
Submit a PR for this,
https://github.com/marisolpalmero/GREEN-bof/pull/69

**Comment by marisolpalmero** [comment]
Approved PR #69 . Please if there is a concern, let's open a new issue, or let's discussed during tomorrow's call
