### ISSUE TITLE
Incorrect assumptions in the BOF description

### ISSUE THREAD

**Issue by cpignata** [marisolpalmero/GREEN-bof#18]
The BOF Request Description starts with a paragraph that in a way equates energy and sustainability.
This is incorrect as a broad assumption.

The text says for example _"Energy-aware networking encompasses deploying and managing network infrastructures to reduce energy consumption, optimize energy efficiency, and minimize environmental impact."_

Perhaps **"Energy-Aware Networking"** needs a normative citation to understand what it is -- lacking that, without **carbon intensity / electricity emission factors**, one can increase energy use and decrease negative environmental impact...

I suggest reading https://ghgprotocol.org/sites/default/files/2023-03/Scope3_Calculation_Guidance_0%5B1%5D.pdf

**Comment by marisolpalmero** [comment]
GHG protocol is not a normative. Scope 3 is not mandatory to be reported.
Scope 3 reporting is optional, but strongly encouraged, and GHG protocol proposes a guideline for the calculation (based on the link above)

**Comment by cpignata** [comment]
@marisolpalmero -- I do not see the relevance of your comment to the actual issue reported

**Comment by marisolpalmero** [comment]
change text with NEW:

"Energy-aware networking involves deploying and managing network infrastructures with the dual goals of optimizing energy use and minimizing environmental impact. "
