### ISSUE TITLE
With a Key Objective in define metrics, why limit their reporting to one method only?

### ISSUE THREAD

**Issue by cpignata** [marisolpalmero/GREEN-bof#19]
The BOF Proposal says (my added emphasis)
_"Key objectives include standardizing terms and definitions for energy metrics, reporting energy consumption usage at different levels in the network **via YANG models**"_

If the key objective is to create metrics, why limit the reporting to YANG models, when there are active drafts with different reporting method (e.g., https://datatracker.ietf.org/doc/draft-pignataro-eimpact-icmp/ )

**Comment by billwuqin** [comment]
See related discussion in another github
https://github.com/billwuqin/Green-Energy-Network/issues/4

**Comment by cpignata** [comment]
Somewhat problematic to have all the comments split across repositories...

Agreed that "ICMP" is too specific. However, "Other methods of transporting green metrics" should not be precluded...

**Comment by marisolpalmero** [comment]
Protocol or metrics consumption is addressed under Philatelist framework proposal. Philatelist addresses how to consume from any protocol. Specific protocol extension might not be short-term approach.
