### ISSUE TITLE
Charter -- Energy-Aware and Sustainability are not the same

### ISSUE THREAD

**Issue by cpignata** [marisolpalmero/GREEN-bof#21]
This proposed charter includes a para that reads:

_Energy-aware networking encompasses deploying and managing network infrastructures to reduce energy consumption, and minimize environmental impact. This will involve technologies to monitor energy consumption, evaluate the effectiveness of energy saving polices, use control strategies to improve energy efficiency, and foster sustainability in network operations._

One can increase energy consumption to reduce environmental impact. There are built-in assumptions in this paragraph that would send the whole effort in the wrong direction if taken as-is.

Please c.f., _GHG Protocol Standard_, Scope 3 Category 11.

**Comment by tony1athome** [comment]
This seems redundant with issue #18.

**Comment by cpignata** [comment]
Issue #18 is applicable to the BOF Request document, Issue #21 is applicable to the Charter.
That said, yes, so long as text from both files keeps in sync, it is redundant.

**Comment by marisolpalmero** [comment]
modify the paragraph to this NEW one: 

Energy-aware networking involves deploying and managing network infrastructures with the dual goals of optimizing energy use and minimizing environmental impact. This includes adopting technologies to monitor and effectively manage energy consumption, evaluating the environmental benefits of energy-saving policies beyond just reducing consumption, implementing control strategies that enhance overall energy efficiency, and promoting sustainable practices in network operations. It also recognizes that, in some cases, strategic increases in energy use from sustainable sources can lead to long-term environmental improvements.

**Comment by cpignata** [comment]
@marisolpalmero -- is there an existing normative definition of "energy-aware networking", or is it a neologism you are crafting? If the former, a citation would help. If the latter, a definition would help.

Now, if it is the latter, and the definition is 
_"Energy-aware networking involves deploying and managing network infrastructures with the dual goals of optimizing energy use and minimizing environmental impact"_

Then I object, since the name "energy-aware" ought to not be used for optimizing "energy and something else"/
