### ISSUE TITLE
Charter -- Background and Motivation

### ISSUE THREAD

**Issue by cpignata** [marisolpalmero/GREEN-bof#22]
The first paragraph includes the following: _"e.g., work on energy efficiency metrics and various technology improvements."_

This needs more explicit clarity:
1. What exact "work on energy efficiency metrics"?
2. What other "various technology improvements"?

---

Another part of the text says +"links, nodes and devices"_.

This needs more explicit clarity:
1. Why nodes and devices and not **components** within them?
2. What is the difference between nodes and devices here?

**Comment by marisolpalmero** [comment]
Applying change to the charter proposal: 
OLD: "links, nodes and devices_"
NEW: "links, devices, devices/components"

explanation to the 2nd comment, there is a dependency between component and device.


For the first comment,  proposal does not discuss the focus of the charter but the motivation.

**Comment by billwuqin** [comment]
Regarding the first comment, the proposed text you quote is from Jari, which is really general comparing with the previous text which list all relevant work in other SDOs and IETF, I think the metric work and technology improvement are referred to relevant drafts listed in BOF proposal, which also include some work from ITU-T SG5 and ETSI TC EE. Summarize what they have done, I think we can use energy effiency metrics and various technology improvement. It is very general.

**Comment by cpignata** [comment]
I would still more precisely qualify "various technology improvements". That is, add precision to the quality of it. Otherwise, materials or photography can be included.
