### ISSUE TITLE
Charter -- extraneous paragraph

### ISSUE THREAD

**Issue by cpignata** [marisolpalmero/GREEN-bof#23]
I'd recommend removing this paragraph, as it adds not value and potentially confuses.

_"Improving operational energy efficiency, as part of global sustainability efforts, may also necessitate enhancing inventory attributes, thereby contributing to a more sustainable lifecycle for network devices. It should also be about actually putting in place technology that improves our energy efficiency and sustainability."_

**Comment by jariarkko** [comment]
It does confuse me a bit, so yes. I think if we enhanced existing YANG inventory attributes with some energy information... that'd be fine. But this seems to be saying something more, maybe about the circular economy? In any case, please clarify!

**Comment by janlindblad** [comment]
While I'm not advocating either stance here, I believe this paragraph hints at some published draft work that connects/maps the energy & power reporting to the inventory components work in the IVY WG.

**Comment by tony1athome** [comment]
Ok, then it would be good to do more than hint. Again, clarity and focus are key.

**Comment by marisolpalmero** [comment]
removed the paragraph, and add a note under Out of Scope:
 Adopting a longer-term approach to global sustainability efforts requires enhancing inventory attributes. This enhancement will contribute to a more sustainable lifecycle for network devices. To ensure the effectiveness and alignment of these efforts, it will be essential to coordinate the work of the GREEN WG with the IVY WG.

**Comment by cpignata** [comment]
I do not feel that's an appropriate, agreed upon note.
