### ISSUE TITLE
Charter -- overscoped?

### ISSUE THREAD

**Issue by cpignata** [marisolpalmero/GREEN-bof#24]
I'd recommend removing this as it is not within a narrow scope -- frankly, not within an IETF scope likely.

_"Creating YANG data models that supply metrics for lifecycle assesment, allowing network devices and components to support circular economy strategies."_

**Comment by janlindblad** [comment]
While I agree this may be better left out from the first iteration, the device life cycle cost/benefit analysis use case is one I often hear queries about from customers.

**Comment by cpignata** [comment]
> While I agree this may be better left out from the first iteration, the device life cycle cost/benefit analysis use case is one I often hear queries about from customers.

Not disputing or supporting that, my point is not about customer discovery or market research.

The point is that it is orthogonal to IETF standardization.

**Comment by tony1athome** [comment]
If it does not produce or directly support a standard, then it belongs in e-impact.

**Comment by marisolpalmero** [comment]
including out of scope note.

**Comment by cpignata** [comment]
What exactly is the note?
In order to provide transparency on disposition of comments, please close with a patch, PR, or specific textual change. 
Like this, it's a black hole.
