### ISSUE TITLE
Charter -- unclear Out of Scope conditional bullet

### ISSUE THREAD

**Issue by cpignata** [marisolpalmero/GREEN-bof#26]
The text says:
* _Routing protocols and energy aware routing algorithms considering green energy factors_

Does that mean that Routing protocols and energy aware routing algorithms that **do not** consider green energy factors (Definition?) are in scope?

**Comment by billwuqin** [comment]
No,  routing protocol extension is not in the scope based on previous discussion of coordination meeting and AD's guideline. I think protocol extension that doesn't take into account factors is also not in the scope, since how it will be relevant to this charter scope?

**Comment by marisolpalmero** [comment]
Routing protocols and energy aware routing algorithms are not considered in scope as explained in the comments. Closing this issue

**Comment by billwuqin** [comment]
Carlos, you really look for perfect,:-), Here is my proposed change to improve the charter text:
OLD TEXT:
"
Routing protocols and energy-aware routing algorithms considering energy factors.
"
NEW TEXT:
"
Routing protocols and algorithms, including those that consider energy factors.
"

**Comment by cpignata** [comment]
Qin @billwuqin -- I am not looking for perfect. I am looking for **clear, transparent, and inclusive**. 
It is clear that @marisolpalmero closed this issue without checking with me, and incorrectly. Without either reading or understanding, and without checking with the issue submitter.

In any case, **YES**, your suggestion addresses my concern. Thanks for responding on a mis-closed issue.
