### ISSUE TITLE
Charter scope -- super over-stretch?

### ISSUE THREAD

**Issue by cpignata** [marisolpalmero/GREEN-bof#27]
Is this really a proposed liason?

* Industry stakeholders and regulatory bodies to ensure alignment with current and future regulatory frameworks.

Seems impractical at best.

**Comment by jariarkko** [comment]
Maybe some toning down would be useful. The title was dependencies and liaisons, this is maybe more of a dependency than a chance to influence through liaisons. But industry collaboration is for sure needed.

**Comment by marisolpalmero** [comment]
comments are addressed on the current proposal.

**Comment by billwuqin** [comment]
This is something being discussed in the previsous coordination meeting,  we agree with you that estabshing liasion with industrial stakeholder and regulatory body is not pratical, we haven't see any other WGs to successfully estalish liasion with regulatory body. But for some organization beyond IETF, such as ETSI TCEE, ITU-T SG5, which has connection with regulatory body, therefore we can indirectly influence regulatory by coordinating with ETSI TCEE, ITU-T SG5.
In the coordination meeting, we also discussed  there are no any WG charter in IETF to list such similar obligation. We have two way to address this:
1.  Take it out to align with other WG charter in IETF
2.  Take Jari's suggestion, to make tone soft, here is my proposed change:
OLD TEXT:
"Industry stakeholders and regulatory bodies to ensure alignment with current and future regulatory frameworks."
NEW TEXT:
"Collaboration with Industry stakeholders and regulatory bodies to ensure alignment with current and future regulatory framework is encouraged."

**Comment by cpignata** [comment]
Thank you @billwuqin for the response. Before diving into the content:
1. First, we are commenting on a **Closed** issue.
2. Second, your response makes it clear that the comment from @marisolpalmero about _"comments are addressed on the current proposal."_ was **incorrect** since it is not addressed.

Now, this is a very generic bullet point about something that ought to be specific. Yes, collaboration is needed, as @jariarkko mentioned, of course. But this bullet does not add much to that.

I'd either take it out, or really tone it down.

BTW -- what is the "coordination meeting"?
