### ISSUE TITLE
[BOF-Request] Scope of proposed WG

### ISSUE THREAD

**Issue by dhruvdhody** [marisolpalmero/GREEN-bof#28]
This text --
````
This working group would develop a suite of short-term 
deliverables aimed at enhancing energy efficiency within 
networks.
````

makes the scope of the WG open-ended. The WG charter is not open-ended but this text gives that impression. I would suggest that this text can be targeted towards the BoF that is -- "The BoF discussion should identify a suite of ..."

**Comment by marisolpalmero** [comment]
included under BofRequestProposal.md
