### ISSUE TITLE
What are the WG goals?

### ISSUE THREAD

**Issue by tony1athome** [marisolpalmero/GREEN-bof#3]
In WGCreationProposal.md, we find three paragraphs that seem to have a great deal of commonality in subject.  These start with: 

"The proposed GREEN metrics WG aims to address these challenges by:",
"The GREEN metrics WG will concentrate on short-term deliverables such as:", and
"The GREEN WG will aim to develop standards and guidelines that:"

Each of these is followed by 3 bullets, leading one to believe that there are about 9 different deliverables at play.  This seems confusing.  What is the WG going to do? What is in scope? You've listed what's out of scope. This needs more focus.

**Comment by marisolpalmero** [comment]
Together with Qin, New Proposal has been created and updated under  "GreenCharterProposal.md" file, considering the Issues&PR's requests in Qin's repo and Issues under this repo.
