### ISSUE TITLE
Understanding the power / energy metrics

### ISSUE THREAD

**Issue by luismcontreras** [marisolpalmero/GREEN-bof#33]
Something that is not 100% clear to me is how to work with the power / energy metrics that coudl be collected in a given point of time. We know well other networking metrics such as latency, jitter, bandwidth, etc where spurious behaviors can be identified and outliers ignored. I'm not sure of this is the same case for power / energy metrics.

So, in addition to the collection and aggregation of metrics I think it would be great to include some indications on how to use or interpret them, how the handle, etc. It would help to create a common understanding between producers and consumers of such metrics.

**Comment by janlindblad** [comment]
Agree completely, we have to work something out and agree. Just one simple example: If you have a 100 power-usage values collected from 100 different devices during the last 5 minutes, does it make sense to just add the latest numbers together? Would linear interpolation produce better values?

**Comment by tony1athome** [comment]
That entirely depends on what you're trying to accomplish. If you're trying to compute an optimal topology, then adding them together is pointless.  Similarly, linear interpolation doesn't help. It might be more effective to compute which ASIC is most power inefficient at its current loading and then redirect traffic away from it.

Alternately, If you're doing path computation, you might want to use those power readings to determine the most power efficient ASICs on the path and use that as part of path computation.

**Comment by marisolpalmero** [comment]
include the text: "Create a unified document that includes both the energy consumption metrics and their associated YANG data models, along with guidance on how to use, interpret, and handle them."

**Comment by marisolpalmero** [comment]
it is included under Goal and Scope section
