### ISSUE TITLE
[Charter] RFC 6988

### ISSUE THREAD

**Issue by dhruvdhody** [marisolpalmero/GREEN-bof#34]
> RFC 6988 provides some requirements and guidelines for monitoring and managing energy usage in network devices. The GREEN working group will examine that work with a view to re-using it where possible, and developing new requirements according to current use cases and applications. 

Should creating new requirements or RFC6988bis of sorts be really needed? Does it help with the rest of the charter text which is more focused on metrics?

**Comment by dhruvdhody** [comment]
Thanks for a good conversation during the call, that cleared some things up! 
We need to be more explicit on what we are going to do with EMAN WG output -  
- are we going to do a bis
- are we going to come up with additional requirements and map the existing ones to the YANG framework
- are we going to map existing MIBs to YANG
- something else...
Let's be explicit about this in the charter text!

**Comment by tony1athome** [comment]
As I understand it, we do a bis document when we are making minor tweaks to an existing document. If we are making wholesale changes, that should be a new RFC. 

It seems very early to be deciding that. For that matter, we haven't even decided *if* we have new requirements. I would suggest adding "if necessary" to the existing text.

**Comment by marisolpalmero** [comment]
I understand bis will not be considered.

There is a new thread in the green-bof under Subject "Green requirements, and comparison to the EMAN requirements & framework"

**Comment by billwuqin** [comment]
Yes, after revisiting EMAN requirements, it looks power control described in RFC6988 is more applied to Endpoint device in the office network or home network, see IEEE1621 Power State Set in https://www.iana.org/assignments/power-state-sets/power-state-sets.xhtml#ieee1621 and https://standards.ieee.org/ieee/1621/3344/
so the question is do we want to apply power state control in the same way as consumer devices for network devices? Do we want to benchmark the power saving level of network device, in the similar way as consumer device such as air conditioner, 
Also power state seems not take into account other factors traffic throughput. 

It looks what we can learn from EMAN requirements, is generic terminology they introduce, but how to monitor energy consumption and control consumption using the same YANG interface is something not covered by EMAN requirements and solution.

So my analysis, is that we will not look for do the bis for RFC6988.

**Comment by marisolpalmero** [comment]
Keeping it open for now, until there is consensus on the specifics differentiating from GREEN WG proposal. This is a good point to cover on the agenda for GREEN bof.

**Comment by billwuqin** [comment]
I think we can close this open issue with several proposed changes we integrated recently.
https://github.com/marisolpalmero/GREEN-bof/pull/77
https://github.com/marisolpalmero/GREEN-bof/pull/79
