### ISSUE TITLE
environmental efficiency 

### ISSUE THREAD

**Issue by emile22** [marisolpalmero/GREEN-bof#36]
It seems preferable to start with "Environmental efficiency for communication systems" to cover both energy (more monitored aspects) and resources (more inventory related) efficiency gains.

**Comment by jariarkko** [comment]
In general yes, but ... is this working group addressing the inventory/circular economy aspects?

**Comment by marisolpalmero** [comment]
included the following changes in the charter proposal:
Remove from the Background section:
“Improving operational energy efficiency, as part of global sustainability efforts, may also necessitate enhancing inventory attributes, thereby contributing to a more sustainable lifecycle for network devices.”
 
And for the Scope section:
“   - Creating YANG data models that supply metrics for lifecycle assessment, allowing network devices and components to support circular economy strategies.”
 
 
And adding a paragraph to Out of Scope:
 
Adopting a longer-term approach to global sustainability efforts requires enhancing inventory attributes. This enhancement will contribute to a more sustainable lifecycle for network devices. To ensure the effectiveness and alignment of these efforts, it will be essential to coordinate the work of the GREEN working group with the IVY WG.
