### ISSUE TITLE
What's an RPC?

### ISSUE THREAD

**Issue by jariarkko** [marisolpalmero/GREEN-bof#37]
The text says:

Providing configuration or YANG RPCs to influence and optimize energy usage in network devices, including energy saving capabilities.

What's an RPC? Please expand acronym and/or explain. 

(And I still think "influence and optimize" is pretty vague.)

**Comment by billwuqin** [comment]
It is remote procedure calls，see RFC7950 fore moe usage. it can be defined as part of YANG model, YANG RPCs can be seen as Policy control which can be used to enforce energy efficiency strategy or install policy to provide network optimization.

**Comment by tony1athome** [comment]
Could we just say:

Provide YANG models to control and optimize energy usage ...

**Comment by marisolpalmero** [comment]
modified based on Tony's note
