### ISSUE TITLE
ADD NOGs in the "Dependencies and Liaisons" section of Charter 

### ISSUE THREAD

**Issue by becha42** [marisolpalmero/GREEN-bof#38]
My suggestion is to add one more bullet under "Dependencies and Liaisons" 

- Industry stakeholders and network operators , to inform them of the standardisation development  & gather feedback about operational practices requirements - specifically via national Network Operators Groups (NOGs) and regional Communities such as RIPE, APNIC, NANOG ; IXPs, Data Center Associations (etc)

**Comment by billwuqin** [comment]
I think this is really good suggestion or propsal, but in IETF, we have never done this before,  not sure we should apply this bullet  only to this proposed WG, I think it can be applied to all IETF WG which require soliciting feedback from Operator community.

**Comment by tony1athome** [comment]
Operators are supposed to come to IETF...

**Comment by marisolpalmero** [comment]
Closing this issue. No changes required
