### ISSUE TITLE
Charter, Milestones.

### ISSUE THREAD

**Issue by tony1athome** [marisolpalmero/GREEN-bof#47]
We have two milestones for frameworks.  Are these somehow getting standardized? If not, they should not be work product.

Implementations are not a WG deliverable.

The use cases document should be the first thing we do.

**Comment by marisolpalmero** [comment]
Addressed in the current proposal, only one call out to the framework (Work Items section):
"An informational document defining Framework for Energy metrics collection and aggregation to support incremental deployment of new energy efficiency metrics."
