### ISSUE TITLE
BoF request, Description

### ISSUE THREAD

**Issue by tony1athome** [marisolpalmero/GREEN-bof#48]
s/links, nodes, and devices/components/

OLD
Key objectives include standardizing terms and definitions for energy metrics, reporting energy consumption usage at different levels in the network via YANG models, and providing YANG RPCs for better energy management. 

NEW
Key objectives include standardizing terms and definitions for energy metrics, and YANG models for reporting energy consumption usage and performing energy management. 

I suggest that we delete the sentence about frameworks until we understand what we're actually doing.

**Comment by marisolpalmero** [comment]
added Tony. If this is fine with you, as discussed during the call today, I would not delete/modify framework sentences, until we don't get the review from Jan.
