### ISSUE TITLE
Simplifying the first sentence

### ISSUE THREAD

**Issue by jariarkko** [marisolpalmero/GREEN-bof#5]
The first sentence is a bit long. And also starts with a very standards-oriented angle which is important but maybe the other reasons for this work are even more important. And links don't generally consume energy (or am I missing some special link type that does that?), devices attached to do.

I suggest making this change:

OLD:
As the imperative to improve energy efficiency gains momentum (e.g., ITU-T SG5 has been tasked with development of energy efficiency metrics, KPI, ETSI TCEE works on environmental efficiency related standards covering server, data storage, network equipments), network operators increasingly focus on understanding energy consumption usage across links,nodes and devices within their networks.
NEW:
Energy efficiency gains for communication systems are highly sought after, for environmental, business, and technical reasons. Network operators increasingly focus on understanding energy consumption usage across their networks. This influences of course also standards organizations in the information technology field, e.g., work on energy efficiency metrics and various technology improvements.

**Comment by marisolpalmero** [comment]
resolved as part of the PR based on new branch billwuqin-patch-1. Merged resolved!
