### ISSUE TITLE
Incorrect assumptions in the BOF description

### ISSUE THREAD

**Issue by cpignata** [marisolpalmero/GREEN-bof#52]
As Issue #18 was closed without checking with the submitter (or list (or...)), and I cannot re-open, new Issue.

I object to a term that is "X-aware networking" to mean "Optimize X and Alpha/Beta/Gamma".

**Comment by billwuqin** [comment]
I suggest to repace X-aware networking into energy effiency network management.  Energy Efficiency has been widely adopted by ITU-T and ETSI
