### ISSUE TITLE
BoF request: Relevant Internet-drafts

### ISSUE THREAD

**Issue by tony1athome** [marisolpalmero/GREEN-bof#54]
Could we please make these links to the drafts?

**Comment by marisolpalmero** [comment]
including 

  - Terminology 
       - Candidate documents:[draft-cparsk-eimpact-sustainability-considerations](https://datatracker.ietf.org/doc/draft-cparsk-eimpact-sustainability-considerations/)
     - Power metrics collection and aggregation framework.
       - Candidate documents: [draft-lindblad-tlm-philatelist](https://datatracker.ietf.org/doc/draft-lindblad-tlm-philatelist), [draft-kll-yang-label-tsdb](https://datatracker.ietf.org/doc/draft-kll-yang-label-tsdb), [draft-cx-opsawg-green-metrics](https://datatracker.ietf.org/doc/draft-cx-opsawg-green-metrics)
     - Use Cases:
       - Candidate documents: [draft-almprs-sustainability-insights](https://datatracker.ietf.org/doc/draft-almprs-sustainability-insights)
     - YANG model for power consumption observability and energy saving management.
       - Candidate documents: [draft-li-ivy-power](https://datatracker.ietf.org/doc/draft-li-ivy-power); [draft-cwbgp-ivy-energy-saving-management](https://datatracker.ietf.org/doc/draft-cwbgp-ivy-energy-saving-management); [draft-petra-path-energy-api](https://datatracker.ietf.org/doc/draft-cwbgp-ivy-energy-saving-management); [draft-opsawg-poweff](https://datatracker.ietf.org/doc/draft-opsawg-poweff)
