### ISSUE TITLE
Updated wording about "the framework"

### ISSUE THREAD

**Issue by janlindblad** [marisolpalmero/GREEN-bof#55]
On the May 13 BoF meeting I got the action point to propose updated wording about "the framework" (meaning the collection framework that is mentioned in the charter proposal).

It seems I can't issue PRs towards this repo, so I will submit my proposed text changes like this:

Edit 1
OLD:
As models and metrics are developed and standardized, there might need to be a transition period where some of the equipment in the field does not yet support the new models and metrics. During this period, it will be necessary to map legacy metrics to the new models to enable incremental deployment of the new metrics and mechanisms.
NEW:
As models and metrics are developed, standardized and implemented in production networks, it will take many years before nearly all equipment in the field supports the new models and metrics. Therefore it will be necessary to map legacy metrics to the new models and allow a wide variety of collection mechanisms. Specifically, even though the collection process itself is modeled in YANG, devices cannot generally be assumed to have the data which is to be collected available in any YANG-based management interface.

Edit 2
OLD:
A framework that will enable the collection, aggregation and consumption for mentioned metrics and attributes.
NEW:
Develop or select a framework that will enable the collection, aggregation and consumption of mentioned metrics and attributes developed in the WG from existing and new devices of almost every kind.

**Comment by marisolpalmero** [comment]
Jan, I understand for Edit 2 you will replace the two bullets with the new proposed one:
   - A framework that will enable the collection, aggregation and consumption for mentioned metrics and attributes developed in the WG.
   - A framework to enable incremental deployment by mapping legacy metrics, sourced from either dynamic or static data, to the new YANG models developed by the WG.

As discussed yesterday  during the call, if considering circular or environmental related attributes are out of the scope for the GREEN WG proposal and the collaboration might be open with IVY WG, will you consider following text as replacement:
NEW:
Develop or select a framework that will enable the collection, aggregation and consumption of mentioned metrics and attributes developed in the WG, or other IETF WGs, from existing and new devices of almost every kind.

**Comment by marisolpalmero** [comment]
modifying the text as given by Jan. As Out of Scope considers the longer-term approach for global sustainability efforts
