### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by ronbonica** [marisolpalmero/GREEN-bof#57]
Can I suggest that the WG has exactly two milestones. These are:

- A very short terminology document
- A YANG model

The terminology document introduces the concept of a network element component (e.g., switch interface board, line card, port). It also introduces the power status of each component (e.g., Up, Down). Finally, it introduces power management metrics for each component. The following are examples:

- Instantaneous power consumption (in Watts)
- Utilization (in bits per second)
- Efficiency (in Megabits per Watt)

The YANG model presents status and metrics for each component.

The metrics described in the terminology document will most likely be distributed by routing protocols. However, the WG will not work on routing protocols. It will only define the metrics.

**Comment by billwuqin** [comment]
We are almost getting there.

**Comment by marisolpalmero** [comment]
closing for now. Please bring it up if there is a need to address a comment. Consensus is not final, but getting there.
