### ISSUE TITLE
(coordination) Redundant

### ISSUE THREAD

**Issue by boucadair** [marisolpalmero/GREEN-bof#60]
https://github.com/marisolpalmero/GREEN-bof/blob/b203d3669419080e882717309416929c9e6be665/GreenCharterProposal.md?plain=1#L36C194-L36C330

This part is redundant with the what is listed under the coordination section. I would simplify here. Thanks.

**Comment by billwuqin** [comment]
Good, Fixed

**Comment by billwuqin** [comment]
Fixed with proposed text change to the charter
