### ISSUE TITLE
Support documents

### ISSUE THREAD

**Issue by boucadair** [marisolpalmero/GREEN-bof#61]
https://github.com/marisolpalmero/GREEN-bof/blob/b203d3669419080e882717309416929c9e6be665/GreenCharterProposal.md?plain=1#L41

Suggest to make it explicit this is a support document and that it might not be necessary published as an RFC. 

It is better to set the expectation to avoid frustration, etc.

**Comment by billwuqin** [comment]
Related to #16 raised by Suresh.

**Comment by boucadair** [comment]
#16 is a distinct issue, IMO. 

Please see the PR https://github.com/marisolpalmero/GREEN-bof/pull/68 for the issue I raised.

**Comment by billwuqin** [comment]
Okay, the PR is reasonable, I will integrate it in, thanks.
