### ISSUE TITLE
YANG Models

### ISSUE THREAD

**Issue by boucadair** [marisolpalmero/GREEN-bof#62]
https://github.com/marisolpalmero/GREEN-bof/blob/b203d3669419080e882717309416929c9e6be665/GreenCharterProposal.md?plain=1#L21C1-L21C123

Not evident if this item is the same or complementary to the YANG models in the second bullet. I suggest to have one single bullet for the various YANG models.

**Comment by billwuqin** [comment]
from bullet 2 to bullet 4, I think the intention is to document in one single YANG document, you can see this from the number of work items we proposed. Bullet 4 you are referred to RPC procedure proposed for energy usage optimization, how energy efficiency metrics are used is described in bullet 3.

**Comment by boucadair** [comment]
Thanks for clarifying, Qin. 

Still, I don't think this is clear enough.  Here is the current text we have:

> - Developing YANG models or augmenting existing models to enable controlling and reporting of energy usage through metrics and attributes at component, device, and network levels.
> - ...
> - Providing YANG models to control and optimize energy usage in network devices, including energy saving capabilities.

What about:

* have one single bullet about YANG model(s) to capture the intent
* delete the "augmenting existing models" (because that's still a module).

**Comment by marisolpalmero** [comment]
proposal is adjust to the comments under this issue. Closing it.
