### ISSUE TITLE
Standalone terms doc

### ISSUE THREAD

**Issue by boucadair** [marisolpalmero/GREEN-bof#63]
https://github.com/marisolpalmero/GREEN-bof/blob/b203d3669419080e882717309416929c9e6be665/GreenCharterProposal.md?plain=1#L43

I'm not sure whether a separate item is needed for the terminology if we maintain the framework item. Not sure how to structure that to leave it to the WG to decide which approach to follow.

**Comment by billwuqin** [comment]
Common terminology and definitions are needed to make sure everyone have consistent understanding on energy efficiency management. We have chopped down two frameworks into one framework, the framework focus on incremental update based on  motivation and background discussion.

**Comment by marisolpalmero** [comment]
it has been address in PR #69 .
