### ISSUE TITLE
What about the control part

### ISSUE THREAD

**Issue by boucadair** [marisolpalmero/GREEN-bof#64]
https://github.com/marisolpalmero/GREEN-bof/blob/b203d3669419080e882717309416929c9e6be665/GreenCharterProposal.md?plain=1#L73

Only reporting is mentioned here, while the key contribution of this effort is to control and adjust the various tweaking out there. I suggest to call that out in the milestone. Thanks.

**Comment by billwuqin** [comment]
I need to scope down for the charter, I agree the key contribution of this effort, this can be documented as part of YANG model work as I clarified earlier.

**Comment by marisolpalmero** [comment]
text has been changed on milestones:
"
* Publish YANG models for operational energy efficiency related metrics. While metrics are valuable, they should be leveraged to guide and inspire changes in operational practices to improve energy efficiency and sustainability practices. (Q2 2025)
* Develop a framework for incremental deployment of an energy-aware tools management (Q3 2025).
"
closing the issue
