### ISSUE TITLE
Too much frameworks

### ISSUE THREAD

**Issue by boucadair** [marisolpalmero/GREEN-bof#65]
https://github.com/marisolpalmero/GREEN-bof/blob/b203d3669419080e882717309416929c9e6be665/GreenCharterProposal.md?plain=1#L72

I'm having troubles with item 2 and the other frameworks mentioned in the list. Some of them can be simple sections rather than standalone documents. We don't have that visibility yet, so please consider merging items and leave it to the WG to do the right decision.

**Comment by billwuqin** [comment]
Fixed, thanks.
