### ISSUE TITLE
Listing candidate I-Ds in a Charter

### ISSUE THREAD

**Issue by boucadair** [marisolpalmero/GREEN-bof#67]
https://github.com/marisolpalmero/GREEN-bof/blob/3f60e5f02c5f32bb78958fcf808742abb37d3655/GreenCharterProposal.md?plain=1#L42

I suggest to delete the candidate drafts.

Listing a draft in the charter is not a commitment that a draft will be adopted or that others that are not listed here won't be considered by the WG.

**Comment by billwuqin** [comment]
Agree, this is also related to Suresh filed issue, #16

**Comment by marisolpalmero** [comment]
I'm good deleting them. This is also related to PR #66. 

Having said this, I understand we are ok to leave them listed under the BoF proposal, right? 
Should we still need to add context under the BoF proposal?

**Comment by boucadair** [comment]
> Having said this, I understand we are ok to leave them listed under the BoF proposal, right?

Listing them there is definitely useful. Thanks.
