### ISSUE TITLE
Unclear work item re: influence & optimize 

### ISSUE THREAD

**Issue by jariarkko** [marisolpalmero/GREEN-bof#7]
The below item seemed under-specified to me:

"Providing configuration or YANG RPCs to influence and optimize energy usage in network devices, including energy saving capabilities."

What types influence and optimization are envisioned? If this is about turning on power-saving, micro sleep, or power-off capabilities, please say so. If it is something else, say it. As it is currently, it is pretty open ended.

**Comment by raszuk** [comment]
IMO it would be premature to require specific enumeration of those elements in the charter. To me this line should be kept broad and open to encourage innovation.

**Comment by marisolpalmero** [comment]
I agree to leave it open. As Optimization use cases from my experience are not limited.

**Comment by marisolpalmero** [comment]
it doesn't apply on the current proposal. Work items section has been changed. Having said that, we should keep it in the background as a differentiator with EMAN approach.
