### ISSUE TITLE
short term versus long term: capabilities of legacy device

### ISSUE THREAD

**Issue by emile22** [marisolpalmero/GREEN-bof#70]
wrt to the agenda of last bof preparation call : 
		"3. Green Charter status update
		   o YANG model work will be based on extensions to the inventory where possible in collaboration with in collaboration with IVY.
		      * is Capability of devices long term goal or short term goal?"

The  wording of this question is really inapropriate  as there are capabilities which are urgently needed for assessing legacy devices migration to sustainability, see https://datatracker.ietf.org/doc/draft-stephan-legacy-path-eco-design/ . The charter should start by publishing very quickly a BCP on this in // of the works identified as short term.

**Comment by marisolpalmero** [comment]
PR #74 is submitted. Checking with Daniele and will approve PR based on his comments. Closing for now the issue
