### ISSUE TITLE
Energy Efficiency or Green?

### ISSUE THREAD

**Issue by cpignata** [marisolpalmero/GREEN-bof#71]
I still find the somewhat round-about characterization of the motivation and goals of the proposal confusing.
I had opened Issues #18 , #21 , #51 , and #52 about aspects of this, but those were closed.

To re-state in a common Issue (instead of tracking all places where this manifests), the current proposed BOF request and Charter say, e.g. (emphasis added by me):
> As the desire to **improve energy efficiency** gains momentum, network operators increasingly focus on **understanding energy consumption** by different links, nodes, and devices/components within their networks. 

This is clear. But the next sentence is (my added emphasis):
> **Network Energy-efficiency management** involves deploying and managing network infrastructures with the dual goals of **optimizing energy use** and **minimizing environmental impact**.

This, not so much. 

There are many reasons why **energy efficiency** is can be sought after, including financial, regulatory, etc., etc., and environmental sustainability as well. 

So:
* If the focus is indeed **improving energy efficiency**, why list sustainability as the only added purpose? Why propose GREEN as the name of the WG?
* If the focus is actually *minimizing environmental impact**, green and sustainability, why not say so explicitly?

It seems as going a roundabout way...

---

Similarly, early text says:
> Energy efficiency gains for communication systems are highly sought after, for environmental, business, and technical reasons. 

And then actually says:
> Network energy-efficiency management involves deploying and managing network infrastructures with the dual goals of optimizing energy use and minimizing environmental impact.

**Comment by billwuqin** [comment]
The focus will be energy efficiency network management, sustainable provide motivation and background, in the first phase, we need to lay foundation for future use cases, requirements.

**Comment by marisolpalmero** [comment]
closing based on comments with the rationale on the focus

**Comment by billwuqin** [comment]
Carlos said:
If the focus is indeed improving energy efficiency, why list sustainability as the only added purpose? Why propose GREEN as the name of the WG?
If improving energy efficiency can contribute to socal good, why not add? I see Sustainable is long term version, can better make this proposed WG to align with IAB E-impact program. GREEN is the acronym I choose based on discussion in the coordination meeting. I thinkg it did reflect energy efficiency purpose, isn't it.
Carlos also said:
"If the focus is actually minimizing environmental impact*, green and sustainability, why not say so explicitly?
" 
As we clarified earlier, this charter break down into several sections including motivation and background, Goal and Scope, etc.
The text you quote is from section on Motivation and Background.
Sustainable is long term version, in the short term we did focus on energy efficiency goal, please check Goal and Scope section, work items section, milestone section, we already make those clear, right?

**Comment by cpignata** [comment]
Thank you for this explanation, @billwuqin ! 

I must admit, it is not clear to me from the write-ups. 

I interpret the current text as "this is about energy efficiency, so let's sneak in circular economy"...

Please clarify the text as per your explanation on this Closed issue.
