### ISSUE TITLE
Proposed Liaisons

### ISSUE THREAD

**Issue by cpignata** [marisolpalmero/GREEN-bof#73]
The proposed charter says

> The GREEN Working Groups will liaise with other SDOs on benchmarking methodologies for collaboration and consultation, mainly:
> * The European Telecommunications Standards Institute (ETSI), particularly with regard to the Technical Committee of Environment Engineering (TCEE).
> * The International Telecommunication Union (ITU), particularly with regard to ITU-T-SG-5.

Are these the top external useful liaisons for energy efficiency? Or for sustainability? Meaning... what is the real scope?

**Comment by billwuqin** [comment]
The idea is to coordinate with both working groups in IETF and the working groups in other SDOs who are responsbile for measurment method specification for the metrics.
ETSI TCEE and ITU-T are responsible for methodology and measurement method for Energy effiency ration composite metrics.

**Comment by marisolpalmero** [comment]
Closing the issue as per comments
