### ISSUE TITLE
Updated text for PR74

### ISSUE THREAD

**Issue by DanieleIETF** [marisolpalmero/GREEN-bof#76]
Updated text for #74 

New text proposed:

OLD
It may be complex and time-consuming to attempt to address all issues related to power consumption and energy efficiency in one step, but it can be practical to select building-blocks that will contribute to the larger effort. The GREEN WG will consider approaches to facilitate the emergence of tools that will serve as a foundation for new energy efficiency strategies.
NEW
It may be complex and time-consuming to attempt to address all issues related to power consumption and energy efficiency in a single step. It can be practical to define building-blocks that enhance both static device capabilities (related to inventory attributes) and dynamic energy efficiency metrics contributing to a more sustainable network device lifecycle. The GREEN WG will provide tools that will serve as a foundation for new energy efficiency strategies. To ensure the effectiveness and alignment of these efforts, the GREEN Working Group will closely coordinate with the IVY Working Group for inventory related extensions.

**Comment by billwuqin** [comment]
Thanks Danielel. I agree with Danielel's proposed change, this can override my PR or consolidated into one.

**Comment by marisolpalmero** [comment]
proposal included in the BOF proposal doc.
