### ISSUE TITLE
circular economy

### ISSUE THREAD

**Issue by raszuk** [marisolpalmero/GREEN-bof#8]
> allowing network devices and components to support circular economy strategies.

I really do not understand how network elements can support or even participate in any form or shape of circular economy - especially  "reuse and recycle" parts of it. 

I am not aware of any network device being able to "reuse" anything. 

And for "recycle" it actually in network device data plane means due to finite data plane pipeline designs and lot's of features enabled on the packets - those packets need to be going via forwarding pipeline again. 

The only thing which comes to mind is to reuse the box network device came in for RMA or if it happens to work fine - recycle it :).

**Comment by marisolpalmero** [comment]
there is a thread open on the mailer:
https://mailarchive.ietf.org/arch/msg/green-bof/Hav3UnprzrjdQmI3sACRyOK2tVM/
As a reply  to:

  *   Drop that bullet
  *   Add a work item to consider at a high level the use cases that might benefit from the models and mechanisms developed by the working group.

[propose to continue discussion on the meeting tomorrow]

Before dropping it, I would like to consider it as a point for discussion during tomorrow’s call.
 
Note:
We have discussed during the previous call and considered the use case approach, where draft-almprs-sustainability-insights is included as candidate for collecting initial use cases.
 
 
 
 
I would like to propose to consider the scope to address additional attributes related to circularity. These attributes could include modularity, material component, recycled material, life-time, etc, which, although not inherent attributes of network devices TODAY; initially they might be detailed in databases or data sheets provided by vendors, and shoud be collected at the controller level. These considerations are part of the proposed extension of the framework.
 
Two use cases:
 
 
Migration Use Cases: Driven by eco-design and circularity principles. As part of the vendor sector, it's noteworthy that Operators and Enterprises now incorporate Environmental, Social, and Governance (ESG) criteria into their vendor selection processes. Eco-design and circular design principles are becoming key determinants in the acquisition of new equipment, as outlined in the French government's eco-design framework (Référentiel général de l'écoconception): https://ecoresponsable.numerique.gouv.fr/publications/referentiel-general-ecoconception/.
 
Note: Eco-design can be summarized as a set of concepts and practices aimed at integrating environmental considerations throughout a product's lifecycle, from design and development to transportation, usage, and disposal.
 
Energy Consumption and Efficiency Driving Optimization: It is clear that one of the objectives of the new WG should be to influence the creation of more energy-efficient network equipment. However, I am curious as to how this will translate into actionable business decisions if we do not support such transitions with quantifiable metrics, especially when businesses are increasingly guided by eco-design and circularity principles throughout the network equipment lifecycle.
 
 
If we would like to consider these two use cases, should this work be part of inventory IVY WG or we should consider it under the new GREEN WG? short-term or long-term?

**Comment by jariarkko** [comment]
The charter has these items:

- Developing YANG models or augmenting existing models to enable reporting of energy usage through metrics and attributes at component, device, and network levels.
- Creating YANG data models that supply metrics for lifecycle assesment, allowing network devices and components to support circular economy strategies.

Both are important, but I would suggest the current focus in the discussions and for is primarily on the first one. I would suggest addressing that. And later updates to the charter/other WGs fo the latter. In particular, it is unclear to me whether YANG data models are the primary issue in circular economy.

**Comment by janlindblad** [comment]
I agree starting with energy usage makes good sense, but we also have use cases listed that involve the cost/benefit analysis for upgrading some network equipment, and then the life cycle data becomes important. Such data could of course be reported without YANG modules, but YANG is great for making data machine readable.

**Comment by becha42** [comment]
Is this a good time & place to mention 
https://datatracker.ietf.org/doc/html/draft-palmero-ivy-ps-almo-01 ?

Is this a good candidate for Work Items?

Can we list it in the "liaisons"?

or is that too much detail?

**Comment by marisolpalmero** [comment]
there is a use case for ALMO, but not short term. There are capabilities in network devices/applications, in ALMO they are called "features", that will consume more power than others.

**Comment by marisolpalmero** [comment]
There is a consensus to collaborate with IVY WG. Please suggest any changes if this is not clear in the current proposal. Closing it for now
