### ISSUE TITLE
A possible new item to the out-of-scope list

### ISSUE THREAD

**Issue by jariarkko** [marisolpalmero/GREEN-bof#83]
A question.

Providing measurements about energy consumption (or even controlling) within a single administrative domain is a clear target for the working group. 

But what about cross-domain use of these measurements? Or, even cross-domain use of the measurements between parties that do not trust each other? It seems to me that this would be a challenging task, whereas the within-my-domain and with-my-trusted-partner situations are more tractable. The latter cases would not involve attempting to prove that measurements are not incorrect or falsified, for instance.

Is there a need to add something to the out-of-scope list?

**Comment by billwuqin** [comment]
Who is "my" in within my-domain, with-my-trusted-parter? Network Operator, ideally, if we deploy hierarchical SDN archicture in this senario, having one controller for each domain, each domain measurement can be collected from each domain, in the charter, we allow both device level model and network level model, if each domain specific controller suppport network level model or network level API, they can measure and report measurement results in a consistent way to multi-domain controller?
but I agree with you that it will be much simpler if we limited solution to single domain, at least single operator domain.

**Comment by billwuqin** [comment]
Addressed in https://github.com/marisolpalmero/GREEN-bof/pull/85/commits/f71b69ddaaa70de94deff9e5882375c5b8e2e20c
