### ISSUE TITLE
Science Based Targets Initiative (SBTi) liaison

### ISSUE THREAD

**Issue by marisolpalmero** [marisolpalmero/GREEN-bof#88]
It could make sense to list one more industry liaison: Science Based Targets Initiative (SBTi). Those are the folks that most of the industry players are using to get a certified transition plan. We should make sure that they can make use of the data output that will be produced as part of the GREEN WG

**Comment by marisolpalmero** [comment]
@billwuqin could you please review and consider?

**Comment by marisolpalmero** [comment]
@billwuqin  could you please review Qin?

**Comment by billwuqin** [comment]
First, IETF is open standard body, any IETF standard work can be accessed by any other orgainzation without any formal liaison relationship.
Second, does Science Based Targets Initiative provide any foundation work for IETF, e.g., measurement method, metric definition, methodology, if the answer is no, I think we don't need to add it to endorse it, make sense?

**Comment by janlindblad** [comment]
We may not need a formal liaison with SBTi, but in every ICT-project I have been involved in, it has always been stressed that it is important to include the most relevant stakeholders early in the design. And the SBTi folks are the primary (expert) recipients of our work, imho. If they don't find our work useful for whatever reason, it will have limited value. It does not necessarily have to be exactly SBTi, there are other relevant organizations as well, even if I think SBTi is the organization that is used by most of the vendors and operators in our business world.

**Comment by billwuqin** [comment]
Jan, Not familar with this SBTi, what data they want to use or built on top of it? Do you have more details of introduction of SBTi's project?

**Comment by marisolpalmero** [comment]
I'm not that familiar with SBTi, as much as I'm with GHG protocol. But this is one of those certifications/recognition that many companies are after today. Having said this, I believe is important to decide who the potential GREEN WG would like the message to be followed. I would like to see how we want to influence those organizations that are leading guidelines and standards on how to account for Scope1, 2, and 3. The purpose of the WG is to develop energy efficiency metrics, and methods for measuring energy consumption in networking devices with the purpose of optimization. From lifecycle assessment, the use phase or running operations is the largest, with a difference, on the energy consumption phase for networking equipment, and these metrics that we are working out should contribute to the translation of carbon emissions more reliably and transparently, to the complete lifecycle. I believe we should bring value to those SBTi, GHG protocol guidelines/standards and certifications. For me, they should be consumers of the metrics and methods that we will be working on

**Comment by janlindblad** [comment]
Thanks @marisolpalmero , exactly my point. We need to connect with the teams that will *use* the information we standardize and enable. I ran a quick google of 10 random ICT company names plus "sbti". 9 out of 10 (google missing) immediately took me to a page that talks about that company's SBTi approved decarbonization plan.

If we don't get the people making these SBTi commitments at each company aware+involved in our work, I'm afraid we won't do much real change in the world.

https://www.cisco.com/c/en/us/about/csr/environmental-sustainability/net-zero.html
https://www.nokia.com/about-us/news/releases/2024/02/26/nokia-commits-to-net-zero-greenhouse-gas-emissions-by-2040/
https://blogs.juniper.net/en-us/corporate-responsibility/expanding-junipers-climate-commitment
https://www.telefonica.com/en/communication-room/press-room/telefonicafirst-telco-in-the-world-with-net-zero-targets-validated-by-sbti/
https://sustainability.att.com/priority-topics/climate-change-ghg
https://aboutv2.rogers.com/wp-content/uploads/TCFD_Report_2022.pdf
https://www.ibm.com/blog/science-based-targets-what-are-the-key-commitments-required/
https://www.aboutamazon.com/news/sustainability/amazons-approach-to-setting-science-based-targets
https://blogs.microsoft.com/on-the-issues/2024/03/14/on-science-based-targets-initiatives-removal-of-net-zero-commitment/

**Comment by janlindblad** [comment]
Ah, and if you don't know of SBTi, you can read about them on their home page:
https://sciencebasedtargets.org/

**Comment by billwuqin** [comment]
I thought the main consumer for GREEN work is network operators, but look into this website, the main players in these field are vertical sector such as power, steel , no?

**Comment by billwuqin** [comment]
> I'm not that familiar with SBTi, as much as I'm with GHG protocol. But this is one of those certifications/recognition that >many companies are after today. Having said this, I believe is important to decide who the potential GREEN WG would like >the message to be followed. I would like to see how we want to influence those organizations that are leading guidelines and >standards on how to account for Scope1, 2, and 3. The purpose of the WG is to develop energy efficiency metrics, and >methods for measuring energy consumption in networking devices with the purpose of optimization. From lifecycle >assessment, the use phase or running operations is the largest, with a difference, on the energy consumption phase for >networking equipment, and these metrics that we are working out should contribute to the translation of carbon emissions >more reliably and transparently, to the complete lifecycle. I believe we should bring value to those SBTi, GHG protocol >guidelines/standards and certifications. For me, they should be consumers of the metrics and methods that we will be >working on

Thank for sharing the information, just to be clear,  the current charter scope has ruled out of GHG protocol, therefore it is not our short term goal to make GREEN connecting to SBTi, but definitely we can consider to establish such connection in the long term, e.g.,we can ask this proposed GREEN to send out a liaison to SBTi to provide Work progress update and draw their interests.
If we can invite SBTi project proponent to come to IETF, and introduce what they are doing, this will also help IETF better understand how IETF work add value to SBTi project. 

Another thing which I am not sure, IS SBTi project a research project or engineering project? As you can see, some long term research topic has been investigated in IRTF NMRG.

**Comment by billwuqin** [comment]
Close this issue based on GREEN Charter refine discussion in August 13.
