### ISSUE TITLE
Allocation per customer/user

### ISSUE THREAD

**Issue by janlindblad** [marisolpalmero/GREEN-bof#89]
In my mind, one of the main purposes for doing this work is to be able to allocate/compute and report the energy spent on behalf of a particular customer/user. I would like that to be included that in the WG scope.

**Comment by billwuqin** [comment]
Usually power grid company will care about energy spent per customer/user, can you provide a concrete use case for this?

**Comment by avtobiff** [comment]
So that the end user of a service can get their climate impact
and use that in their reports.

A service provider can produce their own report for their total
use, but that is of no use for their users/customers. It needs to
be granular per end user.

**Comment by billwuqin** [comment]
> So that the end user of a service can get their climate impact and use that in their reports.
> 
> A service provider can produce their own report for their total use, but that is of no use for their users/customers. It needs to >be granular per end user.

In two cases, I understand service provider's use case.  For end user case, if we have power meter installed for each user/cusomter, I think we have already known energy consumption per user, if we want to translate such energy consumption per user into carbon emission data, it can be done at the user side? 
If we know the total energy consumption of all network devices used by all end users, how do we know end user A consume more energy than end user B?

Maybe the first step is to figure out how energy consumption data is translated into carbon emmission data? I see many airflight company has already provide some carbon emmission data for each flight taking different route from City A to City B in various different country.

**Comment by avtobiff** [comment]
> In two cases, I understand service provider's use case. For end user case, if we have power meter installed for each user/cusomter, I think we have already known energy consumption per user, if we want to translate such energy consumption per user into carbon emission data, it can be done at the user side?

The power meter at the users house can't measure the video streaming
service's energy consumption.

I mean that the use case is to measure the climate impact of a service
that is not at the users house, but elsewhere probably in some data center.


> If we know the total energy consumption of all network devices used by all end users, how do we know end user A consume more energy than end user B?

We don't. But that is a use case that would be good to solve.
To report usage/impact per user.

**Comment by billwuqin** [comment]
Close this issue based on GREEN Charter refine discussion in August 13.
