### ISSUE TITLE
Language re: no consistent view in the industry on terminology

### ISSUE THREAD

**Issue by jariarkko** [marisolpalmero/GREEN-bof#92]
The charter says: "However, there is no consistent view within the industry for terminologies to categorize various type of metrics and measurements."

I'm wondering how widely this applies. In general? Across IT? Maybe we could focus on our part, and just say "Internet industry". This would also allow referencing outside-IETF terminology definitions, should they be found to be reasonable and consistent e.g. in the IT field. I'm not sure that's the case, but the current claim can be read more broadly than just applying to IETF technologies.

**Comment by billwuqin** [comment]
Across ICT? should we say holistic view?
